=== kyleu/pftest/assets/schema/model.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://projectforge.dev/schemas/model.schema.json",
  "title": "Model",
  "type": "object",
  "properties": {
    "name": {
      "description": "the name of the model, lowercase and underscore-delimited",
      "type": "string",
      "minLength": 1
    },
    "package": {
      "description": "single-word package name for this model",
      "type": "string",
      "minLength": 1
    },
    "group": {
      "description": "when set, places this model inside a folder group",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "description": {
      "description": "used in UI and documentation",
      "type": "string"
    },
    "icon": {
      "description": "one of the SVGs available in ./assets",
      "type": "string"
    },
    "ordering": {
      "description": "default SQL ordering when querying this model",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "column": {
            "type": "string",
            "minLength": 1
          },
          "asc": {
            "type": "boolean"
          }
        }
      }
    },
    "search": {
      "description": "additional columns to include in the search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "description": "flags for this model that control generated code",
      "type": "array",
      "items": {
        "enum": ["audit", "big", "count", "external", "menu-hidden", "menu-items", "no-database", "no-service", "no-controller", "no-routes", "public", "search", "softDelete"]
      }
    },
    "title": {
      "description": "overrides the computed title",
      "type": "string"
    },
    "plural": {
      "description": "overrides the computed plural form",
      "type": "string"
    },
    "proper": {
      "description": "overrides the computed proper-case version of the name",
      "type": "string"
    },
    "route": {
      "description": "overrides the computed route",
      "type": "string"
    },
    "config": {
      "description": "a config object for this model; unused",
      "$ref": "config.schema.json#/"
    },
    "columns": {
      "description": "the columns in this model's table",
      "type": "array",
      "items": {
        "$ref": "#/$defs/column"
      }
    },
    "relations": {
      "description": "defines relationships to other models",
      "type": "array",
      "items": {
        "$ref": "#/$defs/relation"
      }
    },
    "indexes": {
      "description": "additional indexes for this model",
      "type": "array",
      "items": {
        "$ref": "#/$defs/index"
      }
    },
    "seedData": {
      "description": "initial seed data for this model, in `[][]string` form",
      "type": "array"
    },
    "links": {
      "description": "additional links to display for this model",
      "type": "array"
    },
    "imports": {
      "description": "additional imports to include when rendering code",
      "type": "array"
    }
  },
  "required": [
    "name",
    "package"
  ],
  "$defs": {
    "column": {
      "type": "object",
      "properties": {
        "name": {
          "description": "the name of this column, in database format",
          "type": "string"
        },
        "type": {},
        "pk": {
          "description": "if set, column will be part of the primary key",
          "type": "boolean"
        },
        "nullable": {
          "description": "if set, null values are allowed",
          "type": "boolean"
        },
        "search": {
          "description": "if set, column will be part of the search",
          "type": "boolean"
        },
        "sqlDefault": {
          "description": "default value, include single quotes for string literals",
          "type": "string"
        },
        "indexed": {
          "description": "if set, column will be indexed",
          "type": "boolean"
        },
        "display": {
          "description": "if set to \"detail\", will omit column from listing tables",
          "enum": ["detail", "tags", "url", "summary"]
        },
        "format": {
          "description": "used for strings, controls output format in UI",
          "enum": ["code", "codehidden", "color", "country", "html", "icon", "image", "json", "linebreaks", "seconds", "select", "si", "sql", "tags", "url"]
        },
        "example": {
          "description": "default example value to use when editing",
          "type": "string"
        },
        "json": {
          "description": "the JSON field name to use when serializing, defaults to [name]",
          "type": "string"
        },
        "values": {
          "description": "when format is \"select\", this controls the available values",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "description": "tags controlling the column's code behavior",
          "type": "array",
          "items": {
            "oneOf": [
              {
                "enum": ["const", "created", "debug-only", "deleted", "derived" ,"link", "list-first", "no-title", "omitempty", "title", "unique", "updated"]
              },
              {
                "type": "string",
                "pattern": "^fn:"
              }
            ]
          }
        },
        "helpString": {
          "description": "emitted it the UI, this is an optional help string",
          "type": "string"
        }
      }
    },
    "relation": {
      "type": "object",
      "properties": {
        "name": {
          "description": "name of this relationship, used as the database FK name",
          "type": "string"
        },
        "src": {
          "description": "columns from source table",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "table": {
          "description": "name of target table",
          "type": "string"
        },
        "tgt": {
          "description": "columns from target table",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "index": {
      "type": "object",
      "properties": {
        "name": {
          "description": "name of the index, used as the database name",
          "type": "string"
        },
        "decl": {
          "description": "declaration, in SQL format, of this index's members",
          "type": "string"
        }
      }
    }
  }
}

=== kyleu/pftest/.projectforge/export/models/relation.json
{
  "name": "relation",
  "package": "relation",
  "description": "Relation Model",
  "icon": "star",
  "ordering": [
    {
      "column": "created"
    }
  ],
  "search": [
    "lower(id::text)",
    "lower(name)"
  ],
  "columns": [
    {
      "name": "id",
      "type": "uuid",
      "pk": true,
      "search": true
    },
    {
      "name": "basic_id",
      "type": "uuid"
    },
    {
      "name": "name",
      "type": "string",
      "search": true,
      "tags": [
        "title"
      ]
    },
    {
      "name": "created",
      "type": "timestamp",
      "sqlDefault": "now()",
      "tags": [
        "created"
      ]
    }
  ],
  "relations": [
    {
      "name": "relation_fk",
      "src": [
        "basic_id"
      ],
      "table": "basic",
      "tgt": [
        "id"
      ]
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/Capital.json
{
  "name": "Capital",
  "package": "capital",
  "description": "Proper case table",
  "icon": "star",
  "title": "Capital",
  "columns": [
    {
      "name": "ID",
      "type": "string",
      "pk": true,
      "search": true
    },
    {
      "name": "Name",
      "type": "string",
      "search": true,
      "tags": [
        "title"
      ]
    },
    {
      "name": "Birthday",
      "type": "timestamp",
      "search": true
    },
    {
      "name": "Deathday",
      "type": "timestamp",
      "nullable": true,
      "search": true
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/reference.json
{
  "name": "reference",
  "package": "reference",
  "description": "Custom Reference",
  "icon": "star",
  "ordering": [
    {
      "column": "created"
    }
  ],
  "search": [
    "lower(id::text)",
    "lower(name)"
  ],
  "columns": [
    {
      "name": "id",
      "type": "uuid",
      "pk": true,
      "search": true
    },
    {
      "name": "custom",
      "type": {
        "k": "reference",
        "t": {
          "pkg": [
            "github.com",
            "kyleu",
            "pftest",
            "app",
            "foo"
          ],
          "k": "Custom"
        }
      },
      "search": true
    },
    {
      "name": "self",
      "type": {
        "k": "reference",
        "t": {
          "pkg": [
            "github.com",
            "kyleu",
            "pftest",
            "app",
            "reference"
          ],
          "k": "SelfCustom"
        }
      },
      "search": true
    },
    {
      "name": "created",
      "type": "timestamp",
      "sqlDefault": "now()",
      "tags": [
        "created"
      ]
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/timestamp.json
{
  "name": "timestamp",
  "package": "timestamp",
  "description": "Timestamps",
  "icon": "star",
  "tags": [
    "softDelete"
  ],
  "columns": [
    {
      "name": "id",
      "type": "string",
      "pk": true,
      "search": true
    },
    {
      "name": "created",
      "type": "timestamp",
      "sqlDefault": "now()",
      "tags": [
        "created"
      ]
    },
    {
      "name": "updated",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "updated"
      ]
    },
    {
      "name": "deleted",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "deleted"
      ]
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/softdel.json
{
  "name": "softdel",
  "package": "softdel",
  "description": "Soft-deleted table",
  "icon": "star",
  "ordering": [
    {
      "column": "created"
    }
  ],
  "tags": [
    "softDelete"
  ],
  "columns": [
    {
      "name": "id",
      "type": "string",
      "pk": true,
      "search": true
    },
    {
      "name": "created",
      "type": "timestamp",
      "sqlDefault": "now()",
      "tags": [
        "created"
      ]
    },
    {
      "name": "updated",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "updated"
      ]
    },
    {
      "name": "deleted",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "deleted"
      ]
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/oddrel.json
{
  "name": "oddrel",
  "package": "oddrel",
  "group": [
    "oddpk"
  ],
  "description": "Odd Rel",
  "icon": "star",
  "ordering": [
    {
      "column": "name"
    }
  ],
  "search": [
    "lower(id::text)",
    "lower(project::text)",
    "lower(path)"
  ],
  "columns": [
    {
      "name": "id",
      "type": "uuid",
      "pk": true,
      "search": true
    },
    {
      "name": "project",
      "type": "uuid",
      "search": true
    },
    {
      "name": "path",
      "type": "string",
      "search": true,
      "tags": [
        "path"
      ]
    }
  ],
  "seedData": [
    [
      "90000000-0000-0000-0000-100000000000",
      "90000000-0000-0000-0000-000000000000",
      "foo/bar"
    ]
  ]
}

=== kyleu/pftest/.projectforge/export/models/group.json
{
  "name": "group",
  "package": "group",
  "description": "Grouped table",
  "icon": "star",
  "columns": [
    {
      "name": "id",
      "type": "string",
      "pk": true,
      "search": true
    },
    {
      "name": "child",
      "type": "string",
      "search": true,
      "tags": [
        "grouped"
      ]
    },
    {
      "name": "data",
      "type": {
        "k": "map",
        "t": {
          "k": "string",
          "v": "any"
        }
      },
      "search": true
    },
    {
      "name": "created",
      "type": "timestamp",
      "sqlDefault": "now()",
      "tags": [
        "created"
      ]
    },
    {
      "name": "updated",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "updated"
      ]
    },
    {
      "name": "deleted",
      "type": "timestamp",
      "nullable": true,
      "sqlDefault": "now()",
      "tags": [
        "deleted"
      ]
    }
  ]
}

=== kyleu/pftest/.projectforge/export/models/oddpk.json
{
  "name": "oddpk",
  "package": "oddpk",
  "description": "Odd PK",
  "icon": "star",
  "ordering": [
    {
      "column": "name"
    }
  ],
  "search": [
    "lower(project::text)",
    "lower(path)",
    "lower(name)"
  ],
  "columns": [
    {
      "name": "project",
      "type": "uuid",
      "pk": true,
      "search": true
    },
    {
      "name": "path",
      "type": "string",
      "pk": true,
      "search": true,
      "tags": [
        "path"
      ]
    },
    {
      "name": "name",
      "type": "string",
      "search": true,
      "tags": [
        "title"
      ]
    }
  ],
  "seedData": [
    [
      "90000000-0000-0000-0000-000000000000",
      "foo/bar",
      "Project 1"
    ]
  ]
}
