=== kyleu/pftest/assets/schema/project.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://projectforge.dev/schemas/project.schema.json",
  "title": "Project",
  "type": "object",
  "properties": {
    "key": {
      "description": "the id of this project, globally unique",
      "type": "string"
    },
    "name": {
      "description": "the human-readable name of this project",
      "type": "string"
    },
    "icon": {
      "description": "one of the SVGs available in ./assets",
      "type": "string"
    },
    "exec": {
      "description": "executable name for this project",
      "type": "string"
    },
    "version": {
      "description": "semver version string",
      "type": "string"
    },
    "package": {
      "description": "full package for this project's module",
      "type": "string"
    },
    "args": {
      "description": "additional arguments to pass when starting this project",
      "type": "string"
    },
    "port": {
      "description": "http port for this project",
      "type": "integer"
    },
    "modules": {
      "description": "the modules used by this project",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ignore": {
      "description": "file patterns to ignore in git and Docker",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "description": "flags for sorting and filtering projects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "info": {
      "description": "additional info about this project",
      "$ref": "info.schema.json#/"
    },
    "theme": {
      "description": "default theme definition for this project",
      "$ref": "theme.schema.json#/"
    },
    "build": {
      "description": "build options for this project",
      "$ref": "build.schema.json#/"
    }
  },
  "additionalProperties": false,
  "required": [
    "key",
    "name",
    "version",
    "package"
  ]
}

=== kyleu/pftest/.projectforge.json
{
  "key": "pftest",
  "name": "Test Project",
  "icon": "robot",
  "exec": "pftest",
  "version": "0.0.0",
  "package": "github.com/kyleu/pftest",
  "port": 41000,
  "modules": [
    "android",
    "core",
    "database",
    "desktop",
    "export",
    "ios",
    "marketing",
    "migration",
    "mysql",
    "notarize",
    "oauth",
    "postgres",
    "search",
    "sqlite",
    "types",
    "upgrade"
  ],
  "info": {
    "org": "kyleu",
    "authorName": "Kyle U",
    "authorEmail": "projectforge@kyleu.com",
    "license": "CC0",
    "homepage": "https://github.com/kyleu/pftest",
    "sourcecode": "https://github.com/kyleu/pftest",
    "summary": "A Test application, built with Project Forge",
    "description": "This app is pretty much totally generated via Project Forge",
    "bundle": "com.kyleu.projectforge.pftest",
    "signingIdentity": "Developer ID Application: Kyle Unverferth (C6S478FYLD)",
    "javaPackage": "com.kyleu.pftest",
    "moduleArgs": {
      "export": {
        "models": [
          {
            "name": "basic",
            "package": "basic",
            "description": "Basic Model",
            "icon": "star",
            "ordering": [{"column": "created"}],
            "search": ["lower(id::text)", "lower(name)"],
            "columns": [
              {
                "name": "id",
                "type": "uuid",
                "pk": true,
                "search": true
              },
              {
                "name": "name",
                "type": "string",
                "search": true
              },
              {
                "name": "created",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["created"]
              }
            ]
          },
          {
            "name": "timestamp",
            "package": "timestamp",
            "description": "Timestamps",
            "icon": "star",
            "tags": ["softDelete"],
            "columns": [
              {
                "name": "id",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "created",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["created"]
              },
              {
                "name": "updated",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["updated"],
                "nullable":true
              },
              {
                "name": "deleted",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["deleted"],
                "nullable":true
              }
            ]
          },
          {
            "name": "version",
            "package": "version",
            "description": "Versioned table",
            "icon": "star",
            "ordering": [{"column": "created"}],
            "history": "revision",
            "columns": [
              {
                "name": "id",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "revision",
                "type": "int",
                "tags": ["revision"],
                "sqlDefault": "1"
              },
              {
                "name": "constcol",
                "type": "string",
                "search": true,
                "tags": ["const"]
              },
              {
                "name": "varcol",
                "type": "map",
                "search": true
              },
              {
                "name": "created",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["created"]
              },
              {
                "name": "updated",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["updated"],
                "nullable":true
              },
              {
                "name": "deleted",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["deleted"],
                "nullable":true
              }
            ]
          },
          {
            "name": "softdel",
            "package": "softdel",
            "description": "Soft-deleted table",
            "icon": "star",
            "ordering": [{"column": "created"}],
            "tags": ["softDelete"],
            "columns": [
              {
                "name": "id",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "created",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["created"]
              },
              {
                "name": "updated",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["updated"],
                "nullable":true
              },
              {
                "name": "deleted",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["deleted"],
                "nullable":true
              }
            ]
          },
          {
            "name": "group",
            "package": "group",
            "description": "Grouped table",
            "icon": "star",
            "columns": [
              {
                "name": "id",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "group",
                "type": "string",
                "search": true,
                "tags": ["grouped"]
              },
              {
                "name": "data",
                "type": "map",
                "search": true
              },
              {
                "name": "created",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["created"]
              },
              {
                "name": "updated",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["updated"],
                "nullable":true
              },
              {
                "name": "deleted",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["deleted"],
                "nullable":true
              }
            ]
          },
          {
            "name": "Capital",
            "package": "capital",
            "title": "Capital",
            "description": "Proper case table",
            "history": "revision",
            "icon": "star",
            "columns": [
              {
                "name": "ID",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "Name",
                "type": "string",
                "search": true
              },
              {
                "name": "Birthday",
                "type": "timestamp",
                "search": true
              },
              {
                "name": "Version",
                "type": "int",
                "tags": ["revision"],
                "sqlDefault": "1"
              },
              {
                "name": "Deathday",
                "type": "timestamp",
                "nullable": true,
                "search": true
              }
            ]
          },
          {
            "name": "mixed_case",
            "package": "mixedcase",
            "title": "Mixed Case",
            "description": "Table and columns with mixed casing",
            "icon": "star",
            "columns": [
              {
                "name": "id",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "test_field",
                "type": "string",
                "search": true
              },
              {
                "name": "another_field",
                "type": "string",
                "search": true
              }
            ]
          },
          {
            "name": "trouble",
            "package": "trouble",
            "description": "Columns with scary names",
            "icon": "star",
            "tags": ["softDelete"],
            "history": "revision",
            "route": "troub/le",
            "columns": [
              {
                "name": "from",
                "type": "text",
                "pk": true,
                "search": true
              },
              {
                "name": "where",
                "type": "int",
                "pk": true,
                "search": true
              },
              {
                "name": "selectcol",
                "type": "int",
                "tags": ["revision"],
                "sqlDefault": "1"
              },
              {
                "name": "limit",
                "type": "string",
                "search": true,
                "tags": ["const"]
              },
              {
                "name": "group",
                "type": "string",
                "search": true
              },
              {
                "name": "delete",
                "type": "timestamp",
                "sqlDefault": "now()",
                "tags": ["deleted"],
                "nullable":true
              }
            ]
          }
        ]
      }
    }
  },
  "theme": {
    "light": {
      "brd": "1px solid #dddddd",
      "ld": "none",
      "fg": "#000000",
      "fgm": "#999999",
      "bg": "#ffffff",
      "bgm": "#eeeeee",
      "lf": "#2d414e",
      "lvf": "#406379",
      "nf": "#000000",
      "nb": "#beb1d7",
      "mf": "#000000",
      "mb": "#e1e1ff",
      "msf": "#000000",
